// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzujmbivyjzcwwqungwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dWptYml2eWp6Y3d3cXVuZ3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTM0MzgsImV4cCI6MjA2MzIyOTQzOH0.8d5e_gwyoywHtZKyQ5FiG-H1AhIMmf4ECQ5fcAQEh64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);